AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EnvironmentName:
    Type: String
    Default: MyElasticBeanstalkEnvironment
    Description: Name of the Elastic Beanstalk environment

  S3Bucket:
    Type: String
    Description: S3 bucket for storing application artifacts

Resources:
  MyRDSDBInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      Engine: "mysql"
      DBInstanceIdentifier: "MyDBInstance"
      MasterUsername: "admin"
      MasterUserPassword: "adminpassword"
      AllocatedStorage: 5
      DBInstanceClass: db.t2.micro
      PubliclyAccessible: true

  MyElasticBeanstalkApplication:
    Type: 'AWS::ElasticBeanstalk::Application'
    Properties:
      Description: 'My Elastic Beanstalk Application'

  MyElasticBeanstalkEnvironment:
    Type: 'AWS::ElasticBeanstalk::Environment'
    Properties:
      ApplicationName: !Ref MyElasticBeanstalkApplication
      EnvironmentName: !Ref EnvironmentName
      SolutionStackName: '64bit Amazon Linux 2 v5.8.0 running Node.js 18'
      OptionSettings:
        - Namespace: 'aws:autoscaling:launchconfiguration'
          OptionName: 'IamInstanceProfile'
          Value: 'aws-elasticbeanstalk-ec2-role'
        - Namespace: 'aws:autoscaling:launchconfiguration'
          OptionName: 'InstanceType'
          Value: 't2.micro'
        - Namespace: 'aws:elasticbeanstalk:environment'
          OptionName: 'ServiceRole'
          Value: 'aws-elasticbeanstalk-service-role'
        - Namespace: 'aws:elasticbeanstalk:application:environment'
          OptionName: 'RDS_HOSTNAME'
          Value: !GetAtt MyRDSDBInstance.Endpoint.Address
        - Namespace: 'aws:elasticbeanstalk:application:environment'
          OptionName: 'RDS_PORT'
          Value: '3306'
        - Namespace: 'aws:elasticbeanstalk:application:environment'
          OptionName: 'RDS_DB_NAME'
          Value: 'mydatabase'
        - Namespace: 'aws:elasticbeanstalk:application:environment'
          OptionName: 'RDS_USERNAME'
          Value: 'admin'
        - Namespace: 'aws:elasticbeanstalk:application:environment'
          OptionName: 'RDS_PASSWORD'
          Value: 'adminpassword'

  MyDeployment:
    Type: 'AWS::ElasticBeanstalk::Version'
    Properties:
      ApplicationName: !Ref MyElasticBeanstalkApplication
      Description: 'Application version for Elastic Beanstalk'
      SourceBundle:
        S3Bucket: !Ref S3Bucket
        S3Key: 'node/hike.zip'
